[workspace]
members = [
    "crates/astera-core",
    "crates/astera-config",
    "crates/astera-ipc",
    "crates/astera",
]
resolver = "3"
exclude = ["fuzz"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.95"

[workspace.dependencies]
astera-core = { path = "crates/astera-core" }
astera-config = { path = "crates/astera-config" }
astera-ipc = { path = "crates/astera-ipc" }
clap = { version = "4.6", features = ["derive"] }
ron = "0.12"
serde = { version = "1", features = ["derive"] }
smol = "2"
thiserror = "2"
smithay = { version = "0.7", default-features = false, features = ["backend_drm", "backend_gbm", "backend_libinput", "backend_session_libseat", "backend_udev", "backend_winit", "desktop", "renderer_gl", "renderer_multi", "renderer_pixman", "wayland_frontend"] }
smithay-drm-extras = { version = "0.1", default-features = false }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
winit = { version = "0.30", default-features = false, features = ["wayland", "x11", "rwh_06"] }
xkbcommon = "0.8"
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client"] }

[workspace.lints.rust]
unsafe_code = "deny"
