[package]
name = "astera"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
default-run = "astera"

[dependencies]
anyhow.workspace = true
astera-config.workspace = true
astera-core.workspace = true
astera-ipc.workspace = true
clap.workspace = true
rustix.workspace = true
serde_json.workspace = true
thiserror.workspace = true
smithay.workspace = true
smithay-drm-extras.workspace = true
input.workspace = true
rand.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
winit.workspace = true
xcursor.workspace = true
wayland-server.workspace = true

[dev-dependencies]
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr.workspace = true
wayland-protocols-misc.workspace = true

[lints]
workspace = true
