[package]
name = "astera"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
default-run = "astera"

[dependencies]
astera-config.workspace = true
astera-core.workspace = true
astera-ipc.workspace = true
ron.workspace = true
smithay.workspace = true
smithay-drm-extras.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
winit.workspace = true
